### ISSUE TITLE
If the initial value is received from a provider the value is null

### ISSUE THREAD

**Issue by VladRoscaDev** [shivanshtalwar0/material_dropdown_formfield#2]
- The value is set using setState and it shows up on the screen, but when _formKey.currentState.validate() si triggered the value in validator:(value){} is null. 

The checking of value should be: if(value==null || value=='') return 'This field is required';
If the widget receives a new value it should call setState on it's new value and handle it internal so that the value that the validator receives is not null.

I will try to research this and help you, but in the mean time this is still an issue.

The problem seems to be here:
```dart
value: value == '' ? null : value,
  onChanged: (dynamic newValue) {
                                state.didChange(newValue);
                                validator(newValue);
                                onChanged(newValue);
                              },
```
At first the value is '' but after I set the value to something it becomes 'something' but the onChangeMethod is not triggered with the newValue.
We have to find a way to force that trigger.

**Comment by shivanshtalwar0** [comment]
That's weird coz it does change value of the state implying onChanged method has triggered
But you saying onChanged method is not triggering can you share your code on codepen

**Comment by VladRoscaDev** [comment]
I will provide some code here because i don't have a working codepen example: 
```dart
class _HolidayPageState extends State<HolidayPage> {
  final GlobalKey<FormState> _formKey = GlobalKey();

  String selectedTransport = '';


  List<Object> transportDataSource = [
    {'display': 'Boat', 'value': 'SHIP'},
    {'display': 'Car', 'value': 'CAR'},
    {'display': 'Plane', 'value': 'AIRPLANE'}
  ];


@override
  void initState() {
    super.initState();
    Future.delayed(Duration.zero, () {
      setState(() {
        holidayModel = ModalRoute.of(context).settings.arguments;
        if (holidayModel != null) {
                   isEditing = true;
          if (isEditing) initValuesIfEdit();
        }
      });
    });
  }

 void initValuesIfEdit() {
    setState(() {
      selectedTransport = holidayModel.transport.toString().split('.').last; //transport is an enum here
    });
  }

 Widget _buildTransportRow(HolidayModel holidayModel) {
    return Container(
      padding: const EdgeInsets.all(8.0),
      child: DropDownFormField(
        inputDecoration: InputDecoration(
          prefixIcon: Icon(Icons.directions),
        ),
        innerTextStyle: TextStyle(fontWeight: FontWeight.bold),
        titleText: 'Transport',
        hintText: 'Choose a means of transport',
        value: selectedTransport,
        onSaved: (value) {
          setState(() {
            selectedTransport = value;
          });
        },
        onChanged: (value) {
          setState(() {
            FocusScope.of(context).requestFocus(FocusNode());
            selectedTransport = value;
          });
        },
        dataSource: transportDataSource,
        textField: 'display',
        valueField: 'value',
        validator: (value) {
          if (value == null || value == '') {
            return 'This field is required';
          }
          return null;
        },
      ),
    );
  }
```

If I select manually a option, it all works fine. But if I have an initial value, the value in the validator is always null.

**Comment by shivanshtalwar0** [comment]
ok, since this problem is inherited from dropdown_formfield, so I think I found a workaround to this problem of state not updating when we programmatically change the value of form field, using TexEditingController, but using this approach will only restrict us to number and string data type as value, which i think covers almost all cases.
let me know what you think.

**Comment by VladRoscaDev** [comment]
I think that using this could be a solution while still preserving a dynamic
```dart
setState((){
 controler..text=value;
})
```
The .. operator is dart "cascade" operator. Useful for chaining operations when you don't care about the return value. This is also dart solution to chainable functions that always return **this**
How does this sound?

**Comment by shivanshtalwar0** [comment]
good news! buddy, flutter team added [DropDownButtonFormField](https://api.flutter.dev/flutter/material/DropdownButtonFormField-class.html) with similar API into latest update I guess  its pointless to keep working on the redundant widget, so I should archive this plugin and should mention people to use official flutter widget

**Comment by VladRoscaDev** [comment]
Nice to hear this from you, hope to see more of your great work on the
pub.dart page! Good luck!

În vin., 15 mai 2020 la 16:41, Shivansh Talwar <notifications@github.com> a
scris:
